apiVersion: v1
kind: Service
metadata:
  name: img-dnn-svc
  labels:
    name: img-dnn-svc
spec:
  type: NodePort
  ports:
    - port: 11211
      nodePort: 31211
      name: img-dnn
    - port: 20000
      nodePort: 31000
      name: launcher
  selector:
    name: img-dnn-server
