apiVersion: v1
kind: Pod
metadata:
  name: memcached-primary
  labels:
    name: memcached-server
spec:
  containers:
    - name: memcached
      image: memcached-hc
      imagePullPolicy: Never
      ports:
        - name: memcached
          containerPort: 11211
          protocol: TCP
