--- Makefile.old	2022-12-15 20:14:54.390669459 -0500
+++ Makefile	2022-12-15 20:13:03.559187584 -0500
@@ -1068,7 +1068,7 @@
 CXX = g++
 CXXCPP = g++ -E
 CXXDEPMODE = depmode=gcc3
-CXXFLAGS = -g -O2
+CXXFLAGS = -g -O2 -std=c++03
 CYGPATH_W = echo
 DEFS = -DHAVE_CONFIG_H
 DEPDIR = .deps
