apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    name: mysql-svc
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      nodePort: 32306
  selector:
    name: mysql-server