apiVersion: v1
kind: Pod
metadata:
  name: xapian-primary
  labels:
    name: xapian-server
spec:
  containers:
    - name: xapian
      image: xapian:latest 
      imagePullPolicy: Never
      env:
      - name: DATA_ROOT
        value: "/src/xapian.inputs"
      - name: TBENCH_WARMUPREQS
        value: "12000"
      - name: TBENCH_MAXREQS
        value: "360000"
      - name: TBENCH_SERVER
        value: "0.0.0.0"
      - name: TBENCH_SERVER_PORT
        value: "11211"
      - name: TBENCH_NCLIENTS
        value: "1"
      - name: SVR_THREADS
        value: "8"
      - name: REQS
        value: "100000000" # Set this very high; the harness controls maxreqs
      ports:
        - name: xapian
          containerPort: 11211
          protocol: TCP
        - name: launcher
          containerPort: 20000
          protocol: TCP
      volumeMounts:
        - name: xapian-vol
          mountPath: /src/xapian.inputs/
        - name: xapian-res
          mountPath: /results
  volumes:
    - name: xapian-vol
      hostPath:
        path: /dev/shm/xapian.inputs
    - name: xapian-res
      hostPath:
        path: /dev/shm/results
