apiVersion: v1
kind: Service
metadata:
  name: iperf3-svc
  labels:
    name: iperf3-svc
spec:
  type: NodePort
  ports:
    - port: 5201
      nodePort: 32000
      name: tcp
  selector:
    name: iperf3
