apiVersion: v1
kind: Pod
metadata:
  name: fibtest-one
  labels:
    name: fibtest-server-one
spec:
  containers:
    - name: fibtest-one
      image: fibtest
      resources:
        requests:
          cpu: "4096m"
      imagePullPolicy: Never
      ports:
        - name: fibtest-one
          containerPort: 20000
          protocol: TCP
  nodeSelector:
    mysql_pod: primary
