apiVersion: v1
kind: Pod
metadata:
  name: ycsb-cl1
  labels:
    name: ycsb-cl1
spec:
  containers:
    - name: ycsb
      image: asarma31/ycsb:latest
      imagePullPolicy: Never
      ports:
        - name: ycsb
          containerPort: 20002
          protocol: TCP
      env:
        - name: YCSB_THREADS
          value: "8"
        - name: YCSB_CORE_RANGE
          value: "1-31"
      volumeMounts:
        - name: ycsb-results
          mountPath: /app/results
  volumes:
    - name: ycsb-results
      hostPath:
        path: /mnt/extra/results/mysql
        type: DirectoryOrCreate
